apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: 'mickey.boxell@oracle.com/cve-test:{{.UUID}}'
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      sha256: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: cve-test
        chartPath: charts/cve-test
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '{{.CURR}}'
